{{- range $name, $cfg := .Values.services }}
{{- if $cfg.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumo-platform.name" $ }}-{{ $name }}
spec:
  type: {{ $.Values.service.type }}
  selector: { lumo.dev/service: {{ $name }} }
  ports: [{ name: http, port: {{ $cfg.port }}, targetPort: http }]
---
{{- end }}
{{- end }}
{{- if .Values.deviceGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumo-platform.name" . }}-device-gateway
  {{- with .Values.deviceGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.deviceGateway.service.type }}
  selector: { lumo.dev/service: governance }
  ports:
    - name: tls-device
      port: {{ .Values.deviceGateway.service.port }}
      targetPort: device-tls
      protocol: TCP
---
{{- end }}
